version: '4'
#OPENCART_PORT=8081 LOCAL_IP=$(hostname -I | grep -o "^[0-9.]*") docker compose up -d
services:

  mariadb:
    image: docker.io/bitnami/mariadb:11.2
    container_name: mariadb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_opencart
      - MARIADB_DATABASE=bitnami_opencart
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    ports:
      - '3336:3306'
    networks:
      opencart-net:

  opencart:
    image: docker.io/bitnami/opencart:4
    container_name: opencart
    ports:
      - '8081:8080'
      - '443:8443'
    environment:
      - OPENCART_HOST=${LOCAL_IP}:${OPENCART_PORT}
      - OPENCART_DATABASE_HOST=mariadb
      - OPENCART_DATABASE_PORT_NUMBER=3336
      - OPENCART_DATABASE_USER=bn_opencart
      - OPENCART_DATABASE_NAME=bitnami_opencart
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'opencart_data:/bitnami/opencart'
      - 'opencart_storage_data:/bitnami/opencart_storage/'
    depends_on:
      - mariadb
    networks:
      opencart-net:

  opencart_tests:
    build:
      context: tests
      dockerfile: Dockerfile
    command:
      - pytest -v --headless true --url http://${LOCAL_IP}:${OPENCART_PORT}
    depends_on:
      - opencart

volumes:
  mariadb_data:
    driver: local
  opencart_data:
    driver: local
  opencart_storage_data:
    driver: local

#networks:
#  test_net:

