services:


  mariadb:
    image: docker.io/bitnami/mariadb:11.2
    container_name: mariadb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_opencart
      - MARIADB_DATABASE=bitnami_opencart
    ports:
      - '3306:3306'

  opencart:
    image: bitnami/opencart:4
    container_name: opencart
    ports:
      - '8088:8080'
      - '443:8443'
    environment:
      - OPENCART_HOST=192.168.10.37:8088
      - OPENCART_DATABASE_HOST=mariadb
      - OPENCART_DATABASE_PORT_NUMBER=3306
      - OPENCART_DATABASE_USER=bn_opencart
      - OPENCART_DATABASE_NAME=bitnami_opencart
      - ALLOW_EMPTY_PASSWORD=yes
    depends_on:
      - mariadb

  tests:
    container_name: opencart_tests
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - opencart
    command: ["pytest"]


volumes:
  mariadb_data:
    driver: local
  opencart_data:
    driver: local
  opencart_storage_data:
    driver: local
